bibfile:
  wos : /home/benjaminpillot/Documents/PRO/ABM_LITERATURE_REVIEW/WoS/DECEMBER_2025/savedrecs_all.bib
  open_alex : /home/benjaminpillot/Documents/PRO/ABM_LITERATURE_REVIEW/OpenAlex/DECEMBER_2025/open_alex.csv
  scopus :
  pubmed:
  doc_type : [article, review]  # Leave doc_type empty if ALL documents must be included in topic modeling


review: # LLM-based review (see https://github.com/PouriaRouzrokh/LatteReview)
  env : /home/benjaminpillot/Documents/PRO/ABM_LITERATURE_REVIEW/.env  # environment file stores API keys
  export_to : /home/benjaminpillot/Documents/PRO/ABM_LITERATURE_REVIEW/PYSYREV/AI_REVIEWED_DOCS/
  batch_size : 100
  api_pause : 30  # time.sleep(api_pause) in order to limit nb of API requests per min during reviewing process
  text_inputs : [title, abstract, keywords]
#  input_description : article title/abstract/keywords
  inclusion_criteria : The scope of the study MUST include
                       the use or development of agent-based models
                       or agent-based simulations FOR addressing
                       energy transition issues.
  exclusion_criteria : 1. The scope of the study DOES NOT include
                      agent-based modelling or energy transition issues;
                      2. The focus of the study is on multi-agent systems,
                      intelligent agents or software agents for solving
                      specific problems such as control strategies;
                      3. The study belongs to another very distant
                      scientific field, such as geology, zoology,
                      biology, medicine, biomedical studies, etc.
  sampling : True  # If True, sample at random the dataset (for test purposes)
  sample_size : 50  # If sampling is True, size of the corresponding random sample to withdraw from the dataset
  decision_rule : majority   # majority, mean
  workflow :    # Workflow consists in as many rounds as defined by the
                # user. Apart the first round, all rounds apply if and only
                # if consensus has not been reached in the previous one
                # (whatever the decision rule selected)
    - round : A
      reviewers : [Reviewer#1, Reviewer#2]  # Reviewer names defined below

    - round : B
      reviewers : [Reviewer#3]

  reviewers :
    - name : Reviewer#1
      reasoning : brief  # brief, cot (see LatteReview)
      model_id : gpt-4o-mini  # Model identifier
      host :
      provider : litellm  # values : litellm, open-ai, ollama
                          # See LatteReview doc for providers
                          # https://github.com/PouriaRouzrokh/LatteReview
      max_tokens : 200
      temperature : 0.9  # temperature parameter is not available for all models
      reasoning_effort :
      backstory : Reviewer#1 is a research scientist with strong expertise
                  in Energy System Modelling for addressing issues related
                  to Energy Transition and net-zero scenarios. Reviewer#1
                  specializes in modeling and analyzing complex energy
                  systems, including renewable integration, grid optimization,
                  demand forecasting, energy policy analysis, and
                  techno-economic assessments. A major focus of Reviewer#1 is
                  literature synthesis and literature reviews — it excels at
                  identifying key themes, comparing methodologies, summarizing
                  findings, and highlighting research gaps in energy systems
                  modeling. Reviewer#1 is highly rigorous  and cautious in its
                  analysis of input texts and articles. It performs thorough and
                  contextualized evaluations of abstracts and full papers,
                  ensuring interpretations are grounded in the methodologies,
                  assumptions, and scope presented by the original authors.
                  It avoids oversimplified generalizations and remains critical
                  of speculative claims or poorly substantiated conclusions.
      additional_context :

    - name : Reviewer#2
      reasoning : brief
      model_id : gpt-4o-mini
      host :
      provider : litellm
      max_tokens : 200
      temperature : 0.1
      reasoning_effort :
      backstory : Reviewer#2 is a seasoned researcher with a PhD in computer
                  science, specializing in agent-based modeling (ABM) and
                  agent-based simulation techniques. Reviewer#2 helps in
                  designing, analyzing, and troubleshooting complex ABMs,
                  drawing from extensive academic and applied research experience.
                  It can help with model formulation, selection of simulation
                  platforms, parameter tuning, validation techniques, and results
                  interpretation. It also assists with writing and reviewing
                  research papers, grant proposals, and academic presentations
                  involving ABM. Reviewer#2 is collaborative, exploratory, and
                  methodical in its reasoning. It ensures technical accuracy while
                  maintaining a tone that invites discussion, experimentation, and
                  iteration. Reviewer#2 shares relevant methodologies and frameworks
                  but remains open to alternative approaches and creative exploration.
                  It can switch between high-level theoretical discussions and practical
                  coding support. It avoids rigid judgment, encourages open-ended
                  inquiry, and flags assumptions that require clarification or validation.
      additional_context :

    - name : Reviewer#3
      reasoning :
      model_id : gpt-4o-mini
      host :
      provider : litellm
      max_tokens : 200
      temperature :
      reasoning_effort : medium
      backstory : Reviewer#3 is a senior MD-PhD researcher with years of experience
                  in conducting systematic reviews in social-ecological systems,
                  Sustainability Science and decarbonisation of the economy. A major
                  focus of Reviewer#3 is literature synthesis and literature reviews —
                  it excels at identifying key themes, comparing methodologies,
                  summarizing findings, and highlighting research gaps in social-ecological
                  studies. Reviewer#3 is highly rigorous and cautious in its analysis of
                  input texts and articles. It performs thorough and contextualized
                  evaluations of abstracts and full papers, ensuring interpretations
                  are grounded in the methodologies, assumptions, and scope presented
                  by the original authors.
      additional_context : Two PhD reviewers have already reviewed this article and
                           disagree on how to evaluate it. You can read their evaluation above.


topic_model:
  doc_dataset : /home/benjaminpillot/Documents/PRO/ABM_LITERATURE_REVIEW/
              PYSYREV/AI_REVIEW_RESULTS/included_articles.csv  # Document dataset for topic modeling
                                                               # corresponds to output after AI review
                                                               # filtering
  export_to : /home/benjaminpillot/Documents/PRO/ABM_LITERATURE_REVIEW/PYSYREV/TOPIC_MODELING/
  distance_name : euclidean

  # Keep n results : keep N best results among all
  # clustering procedures corresponding to n_neighbors,
  # n_components, topic size, and min sample values
  keep_n_results : 15

  hdbscan:
    cluster_selection_method : leaf
    metric : euclidean
    min_topic_size_range : [20, 60]
    min_sample_range : [2, 10]
    topic_size_step : 4
    min_sample_step : 2
    prediction_data : True

  umap:
    metric : cosine
    min_dist : 0.0
    n_neighbors : [5, 10]
    n_components : [5, 10, 15]
    low_memory : False
    random_state : 42

# Bertopic parameters (see https://maartengr.github.io/BERTopic/index.html)
  bertopic:
    transformer_model : allenai/specter2_base
    n_gram_range : bigram
    language : english
    nr_repr_docs : 50  # Number of representative documents for each topic
    calculate_probabilities : True

# Berteley preprocess (see https://github.com/lbl-camera/berteley)
  berteley:
    allow_abbrev : False

  ctfidf:
    bm25_weighting : True
    reduce_frequent_words : True

  topic_distribution:
    window : 8
    stride : 1
    min_similarity : 0.1
    batch_size : 1000
